### ISSUE TITLE
sensors.so: undefined symbol: sensors_get_value

### ISSUE THREAD

**Issue by Skif-off** [max1220/lua-sensor#1]
I tried to run `test.lua`:
```
Lua 5.1: error loading module 'sensors' from file './sensors.so':
	./sensors.so: undefined symbol: sensors_get_value
stack traceback:
	[C]: ?
	[C]: in function 'require'
	./test.lua:1: in main chunk
	[C]: ?
```
Also LuaJIT: I got some additional details:
```
	[C]: at 0x0047e7a2
	[C]: in function 'require'
	./test.lua:1: in main chunk
	[C]: at 0x00404f08
```
Xubuntu 20.04, I tried lm-sensors 3.6.0 (`libsensors5`, by default in 20.04) and 3.4.0 (`libsensors4`).

P.S. Is it possible to move `sensors_init` and `sensors_cleanup` to separate functions (for example, `init` and `cleanup`)? It would be more convenient if we wanted to use `readAll` more than once at a time.

**Comment by max1220** [comment]
Hey, sorry it seams that I had the linker arguments for GCC wrong, that's why you're getting the undefined symbol error.
I fixed it now, you should only need to recompile. I am running Debian testing, and the newer libsensors seems to work fine. 
Also, I've added the separate init and cleanup functions you asked for, plus an extra argument for readAll that when truethy, skips the init and cleanup, so you can perform it yourself. To demonstrate this, I also included a new simple example, a continuous sensor monitor.

**Comment by Skif-off** [comment]
Thanks, works fine!
